language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: bash ./travis/deploy.sh
    skip_cleanup: true
    on:
      all_branches: true
      master: true
notifications:
  email: false